server:
  port: 8081
 
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5